name: Comment Workflow

on:
  issue_comment:
    types: [created, deleted]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Workflow - A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
