name: Notify Watchers

on:
  pull_request:
    types: [closed, reopened]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello, World!"

# jobs:
#   notify-watchers:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Extract PR info
#         id: pr
#         run: echo "Testing workflow"

      # - name: Get watchers from PR comments
      #   id: watchers
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     pr_number=${{ steps.pr.outputs.pr_number }}
      #     echo "Fetching comments for PR #$pr_number"
      #     curl -s -H "Authorization: token $GITHUB_TOKEN" \
      #          "https://api.github.com/repos/${{ github.repository }}/issues/$pr_number/comments" \
      #       | jq -r '.[] | select(.body | test("👀 testbot: Watching PR")) | .body' > comments.txt

      #     echo "Found watchers:"
      #     cat comments.txt

      #     # Extract Slack IDs (from text like @slack_user_id=U12345678)
      #     watchers=$(grep -o 'U[0-9A-Z]\+' comments.txt | sort -u | tr '\n' ',' | sed 's/,$//')
      #     echo "watchers=$watchers" >> $GITHUB_OUTPUT
      #     echo "Watchers: $watchers"
