name: Notify Watchers

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello, World!"
