name: Notify Watchers

on:
  pull_request_review:
    types: [edited, dismissed]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Review watcher
        run: echo "Request review"
