name: Hello World Workflow

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello, World!"
